# Generated by Django 2.2.7 on 2020-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imginfo',
            name='yzm',
            field=models.CharField(max_length=128),
        ),
    ]
